
skillMetadata:
  sections:
    - name: App Info
      fields:
        - type: label
          label: Access OC Transpo data with an App ID and an API key. Please visit the OC Transpo developer website for instructions on how to obtain them.
        - name: AppID
          type: text
          label: App ID
          value: ""
        - name: APIKey
          type: text
          label: API Key
          value: ""
